### ISSUE TITLE
Installing in Oracle Linux

### ISSUE THREAD

**Issue by Paul-Reed** [hardillb/node-red-contrib-googlehome#6]
Could you offer any advice how to install this node in Oracle Linux please and what additional dependencies need to be installed.

Node-RED version: v1.0.3
Node.js  version: v10.19.0
Oracle Linux 4.14.35-1902.300.11.el7uek.x86_64 x64 LE

The installation presently fails (adding via palette manager).

```
-----------------------------------------------------------
2020-04-05T20:31:24.125Z Install : node-red-contrib-googlehome 0.0.6

2020-04-05T20:31:23.356Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-googlehome@0.0.6
2020-04-05T20:31:42.094Z [out] 
2020-04-05T20:31:42.094Z [out] > mdns@2.5.1 install /home/opc/.node-red/node_modules/mdns
2020-04-05T20:31:42.094Z [out] > node-gyp rebuild
2020-04-05T20:31:42.094Z [out] 
2020-04-05T20:31:46.087Z [out] make: Entering directory `/home/opc/.node-red/node_modules/mdns/build'
2020-04-05T20:31:46.089Z [out]   CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
2020-04-05T20:31:46.092Z [err] make: g++: Command not found
2020-04-05T20:31:46.094Z [err] make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 127
2020-04-05T20:31:46.094Z [err] gyp ERR! build error 
2020-04-05T20:31:46.094Z [err] gyp ERR! stack Error: `make` failed with exit code: 2
2020-04-05T20:31:46.094Z [err] gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
2020-04-05T20:31:46.094Z [err] gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
2020-04-05T20:31:46.094Z [err] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2020-04-05T20:31:46.094Z [err] gyp ERR! System Linux 4.14.35-1902.300.11.el7uek.x86_64
2020-04-05T20:31:46.094Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-04-05T20:31:46.094Z [err] gyp ERR! cwd /home/opc/.node-red/node_modules/mdns
2020-04-05T20:31:46.094Z [err] gyp ERR! 
2020-04-05T20:31:46.094Z [out] make: Leaving directory `/home/opc/.node-red/node_modules/mdns/build'
2020-04-05T20:31:46.095Z [err] node -v v10.19.0
2020-04-05T20:31:46.095Z [err] gyp ERR! node-gyp -v v5.0.5
2020-04-05T20:31:46.095Z [err] gyp ERR! not ok 
2020-04-05T20:31:47.170Z [err] npm WARN Master_flow@0.0.1 No repository field.
2020-04-05T20:31:47.170Z [err] npm WARN Master_flow@0.0.1 No license field.
2020-04-05T20:31:47.184Z [err] 
2020-04-05T20:31:47.253Z [err] npm ERR! code ELIFECYCLE
2020-04-05T20:31:47.253Z [err] npm ERR! errno 1
2020-04-05T20:31:47.253Z [err] npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
2020-04-05T20:31:47.253Z [err] npm ERR! Exit status 1
2020-04-05T20:31:47.253Z [err] npm ERR! 
2020-04-05T20:31:47.253Z [err] npm ERR! Failed at the mdns@2.5.1 install script.
2020-04-05T20:31:47.253Z [err] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-05T20:31:47.257Z [err] 
2020-04-05T20:31:47.257Z [err] npm ERR! A complete log of this run can be found in:
2020-04-05T20:31:47.257Z [err] npm ERR!     /home/opc/.npm/_logs/2020-04-05T20_31_47_251Z-debug.log
2020-04-05T20:31:47.273Z rc=1
```

**Comment by hardillb** [comment]
Been a while since I played on a RedHat based distro (used to be hard core Fedora) but you are probably looking for a package called `avahi-compat-libdns_sd-devel`

**Comment by Paul-Reed** [comment]
`avahi-compat-libdns_sd-devel.x86_64 0:0.6.31-19.el7` is already installed.
From the above log, is this line significant? is a further package needed?
`2020-04-05T20:31:46.092Z [err] make: g++: Command not found`
Or should that command be fulfilled from the avahi package.

**Comment by hardillb** [comment]
Err, in that case you have WAY bigger problems.

If you don't have a basic c++ compiler (g++ ) installed then you must have had a bunch of problems installing Node-RED and any nodes that have native components. Basic build tools are normally a pre-req for NodeJS and npm (unless you've done something strange like installed them from a tgz)

I'd suggest you make sure the "Development Tools" group is installed

`sudo yum group install "Development Tools`

**Comment by Paul-Reed** [comment]
I haven't had any problems at all in installing node-RED, or the palette of nodes which have worked fine. This is the first problem that I have hit.
I'm installing all contrib nodes via the palette in the normal manner.
Maybe I've just dodged contrib nodes with native components...

**Comment by Paul-Reed** [comment]
...but, I've now installed `sudo yum group install "Development Tools"` and the node has now successfully installed into the palette.
There doesn't seem to be any connectivity though, but at least it appears to be installed so I'll close this down.
Thanks  Ben

**Comment by Paul-Reed** [comment]
I've just rebooted node-red and noted the below warning. Is this normal?

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
```

**Comment by hardillb** [comment]
The hint is in the word "Warning"
